---
- name: Update system packages
  dnf:
    name: '*'
    state: latest

- name: Install HAProxy
  dnf:
    name: haproxy
    state: present

- name: Create HAProxy configuration file
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: '0644'
  notify: Restart HAProxy

- name: Enable and start HAProxy service
  systemd:
    name: haproxy
    enabled: yes
    state: started

- name: Validate HAProxy configuration
  command: haproxy -f /etc/haproxy/haproxy.cfg -c
  register: haproxy_check
  failed_when: haproxy_check.rc != 0
