---
- name: Reset Kubernetes Cluster
  hosts: kubernetes
  become: true
  vars:
    ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q ec2-user@{{ hostvars["bastion-host"]["ansible_host"] }} -i /home/ec2-user/.ssh/id_rsa -o StrictHostKeyChecking=no"'
  tasks:
    - name: Stop kubelet service
      systemd:
        name: kubelet
        state: stopped
      ignore_errors: true

    - name: Reset kubeadm
      command: kubeadm reset -f
      ignore_errors: true

    - name: Clean up kubernetes directories
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/kubernetes
        - /var/lib/kubelet
        - /var/lib/etcd
        - /home/ec2-user/.kube
        - /root/.kube
        - /etc/cni/net.d
        - /opt/cni/bin
      ignore_errors: true

    - name: Clean up iptables rules
      shell: |
        iptables -F && iptables -t nat -F && iptables -t mangle -F && iptables -X
        ip link delete cni0 || true
        ip link delete flannel.1 || true
      ignore_errors: true

    - name: Clean up container runtime state
      shell: |
        crictl rm -a -f || true
        crictl rmi -a || true
      ignore_errors: true

    - name: Restart container runtime services
      systemd:
        name: "{{ item }}"
        state: restarted
      loop:
        - containerd
        - docker
      ignore_errors: true

    - name: Start kubelet service
      systemd:
        name: kubelet
        state: started
        enabled: true
      ignore_errors: true

    - name: Display reset status
      debug:
        msg: "✅ Node {{ inventory_hostname }} has been reset and is ready for re-initialization"
