---
# Master Playbook to Deploy Complete Kubernetes Cluster
# Run this to execute all steps in sequence

- import_playbook: 01-common-setup.yml
- import_playbook: 02-kubernetes-deps.yml
- import_playbook: 03-master-init.yml
- import_playbook: 04-workers-join.yml
- import_playbook: 05-network-setup.yml
- import_playbook: 06-ha-masters.yml
