---
- name: Uninstall Broken K3S Installation
  hosts: masters
  become: true
  gather_facts: false
  
  tasks:
    - name: Stop K3S service
      systemd:
        name: k3s
        state: stopped
      failed_when: false

    - name: Disable K3S service
      systemd:
        name: k3s
        enabled: false
      failed_when: false

    - name: Check if K3S uninstall script exists
      stat:
        path: /usr/local/bin/k3s-uninstall.sh
      register: uninstall_script

    - name: Uninstall K3S completely
      shell: /usr/local/bin/k3s-uninstall.sh
      when: uninstall_script.stat.exists
      failed_when: false

    - name: Clean up any remaining K3S files
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/systemd/system/k3s.service
        - /etc/systemd/system/k3s.service.env
        - /var/lib/rancher/k3s
        - /etc/rancher/k3s
      failed_when: false

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Verify K3S is completely removed
      shell: systemctl status k3s.service
      register: k3s_check
      failed_when: false

    - name: Display uninstall status
      debug:
        msg: "K3S uninstall complete. Status check: {{ 'Service not found (success)' if 'could not be found' in k3s_check.stderr else 'Service still exists' }}"